using System.Threading;
using DiaryApp.Shared.Abstractions;
using Microsoft.Extensions.Options;

namespace DiaryApp.Server.Processing;

public sealed class SummaryGenerator(IOptions<SummaryOptions> options) : ISummaryGenerator
{
    private readonly SummaryOptions _options = options.Value;

    public Task<string?> SummarizeAsync(VideoEntryDto entry, string? transcript, CancellationToken cancellationToken)
    {
        if (!_options.Enabled || string.IsNullOrWhiteSpace(transcript))
        {
            return Task.FromResult<string?>(null);
        }

        var provider = string.IsNullOrWhiteSpace(_options.Provider) ? "summary service" : _options.Provider;
        return Task.FromResult<string?>($"Summary placeholder generated by {provider} for entry {entry.Title}.");
    }
}
