using System.Threading;
using DiaryApp.Shared.Abstractions;
using Microsoft.Extensions.Options;

namespace DiaryApp.Server.Processing;

public sealed class TranscriptGenerator(IOptions<TranscriptOptions> options) : ITranscriptGenerator
{
    private readonly TranscriptOptions _options = options.Value;

    public Task<string?> GenerateAsync(VideoEntryDto entry, CancellationToken cancellationToken)
    {
        if (!_options.Enabled)
        {
            return Task.FromResult<string?>(null);
        }

        var provider = string.IsNullOrWhiteSpace(_options.Provider) ? "external service" : _options.Provider;
        return Task.FromResult<string?>($"Transcript placeholder generated by {provider} for entry {entry.Title}.");
    }
}
